require 'rubygems'
require 'rake'
require 'date'
require 'rake/gempackagetask'

require 'cucumber/rake/task'

desc 'Default: run the cucumber features.'
task :default => :cucumber

desc "Clean files generated by rake tasks"
task :clobber => [:clobber_rdoc, :clobber_rcov]

Cucumber::Rake::Task.new(:cucumber) do |t|
  t.fork = true
  t.cucumber_opts = ['--format', (ENV['CUCUMBER_FORMAT'] || 'progress')]
end

eval("$specification = begin; #{IO.read('trout.gemspec')}; end")
Rake::GemPackageTask.new($specification) do |package|
  package.need_zip = true
  package.need_tar = true
end
